version: "3.8"

services:      
  using-env-variables:
    image: enviroimage
    build:
      context: .
      dockerfile: ./Dockerfile
    environment: 
      - Device:AzureConnectionString=HostName=yourhub.azure-devices.net;DeviceId=yourdevice;SharedAccessKey=sastoken
      - Device:TelemetryReadDurationInSeconds=45
      - Device:OutputTelemetry=true
